version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns: ["*"]

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: https://github.com/cmhughes/latexindent.pl

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns: ["*"]
