#!/usr/bin/env python3
"""Resolve the source revision used to build a publication artifact."""
from __future__ import annotations

import argparse
import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_URL = "https://github.com/mwyau/wave-motions-in-the-ocean"


def _git(*args: str) -> str | None:
    try:
        return subprocess.check_output(
            ["git", *args], cwd=ROOT, text=True, stderr=subprocess.DEVNULL
        ).strip() or None
    except (OSError, subprocess.CalledProcessError):
        return None


def _tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "{": r"\{",
        "}": r"\}",
        "%": r"\%",
        "#": r"\#",
        "&": r"\&",
        "_": r"\_",
        "$": r"\$",
    }
    return "".join(replacements.get(char, char) for char in value)


@dataclass(frozen=True)
class BuildInfo:
    sha: str
    short_sha: str
    version: str | None
    dirty: bool = False

    @property
    def revision_label(self) -> str:
        # Reader-facing build identity is the source commit. Local working-tree
        # state must not change the label shown in the digital editions.
        return self.short_sha

    @property
    def label(self) -> str:
        if self.version:
            return f"{self.version} ({self.revision_label})"
        return self.revision_label

    @property
    def commit_url(self) -> str:
        if self.sha == "unknown":
            return REPOSITORY_URL
        return f"{REPOSITORY_URL}/commit/{self.sha}"


def current_build() -> BuildInfo:
    explicit_sha = os.environ.get("WAVE_BUILD_SHA") or os.environ.get("GITHUB_SHA")
    sha = (explicit_sha or _git("rev-parse", "HEAD") or "unknown").strip()
    short_sha = sha[:7] if re.fullmatch(r"[0-9a-fA-F]{7,40}", sha) else "unknown"

    # Keep local dirty state available internally, but do not encode it in the
    # reader-facing build label.
    dirty = False
    if not explicit_sha and sha != "unknown":
        dirty = _git("status", "--porcelain") is not None

    version = os.environ.get("WAVE_BUILD_VERSION")
    if not version and os.environ.get("GITHUB_REF_TYPE") == "tag":
        version = os.environ.get("GITHUB_REF_NAME")
    if not version:
        version = _git("describe", "--tags", "--exact-match", "--match", "v[0-9]*")
    if version:
        version = version.strip()

    return BuildInfo(sha=sha, short_sha=short_sha, version=version or None, dirty=dirty)


def write_tex(path: Path, info: BuildInfo) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    version = info.version or ""
    path.write_text(
        "% Generated by scripts/build_info.py; do not commit.\n"
        f"\\providecommand{{\\wavebuildsha}}{{{_tex_escape(info.sha)}}}\n"
        f"\\providecommand{{\\wavebuildshort}}{{{_tex_escape(info.short_sha)}}}\n"
        f"\\providecommand{{\\wavebuildversion}}{{{_tex_escape(version)}}}\n"
        f"\\providecommand{{\\wavebuildlabel}}{{{_tex_escape(info.label)}}}\n"
        f"\\providecommand{{\\wavebuildurl}}{{{_tex_escape(info.commit_url)}}}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--sha", action="store_true")
    group.add_argument("--short", action="store_true")
    group.add_argument("--label", action="store_true")
    group.add_argument("--version", action="store_true")
    group.add_argument("--url", action="store_true")
    group.add_argument("--tex", type=Path)
    args = parser.parse_args()

    info = current_build()
    if args.tex:
        write_tex(args.tex, info)
    elif args.sha:
        print(info.sha)
    elif args.short:
        print(info.short_sha)
    elif args.version:
        print(info.version or "")
    elif args.url:
        print(info.commit_url)
    else:
        print(info.label)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
